### PR TITLE
cmd/geth: register new RootChain contract to dashboard api server.

### PR DESCRIPTION
**Pull request by shingonu**
- [ ] api server url flag
- [ ] connection status
- [ ] manage powerTON with registry

### CODE REVIEW

**Comment by thomashin** [comment]
make dynamic url

**Comment by thomashin** [comment]
manage powerTON with registry

**Comment by thomashin** [comment]
check connection status with file server

**Comment by 4000D** [comment]
Don't make a seperate `pls/registry` package here. these are not related with `pls` package, and `cmd/geth` package are the suitable package to be implemented.

**Comment by 4000D** [comment]
Also managers data should be stored in plasma-evm database and should not depend on the file server.
Consider a case where plasma-evm client runs without dashboard or file server.

**Comment by 4000D** [comment]
I suggest that get additional (and optional) argument of file server url in `geth staking register` command

**Comment by thomashin** [comment]
> Don't make a seperate `pls/registry` package here. these are not related with `pls` package, and `cmd/geth` package are the suitable package to be implemented.

https://github.com/Onther-Tech/plasma-evm/blob/ece47565b0fcafee881b25fddf251de9316f606f/cmd/geth/stakecmd.go#L927

get `abi: unmarshaling empty output` error.

**Pull request closed without merging**
